---
title: "Rstudio Setup"
author: "Connor O'Brien-Stoffa"
date: "2023-02-22"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

 I took a formal semester long class on using R at MSU Denver at the beginning 
of 2022, then when the class ended I didn't use or look at coding for 9 months.
Time to dust off the mind cobwebs for R programming in Rstudio. 

#### vocab

* CRAN 
  + Comprehensive R Archive Network
* mirror  
  + Server with a copy of data from a principal server, different locations
* GUI  
  + Graphics User Interface
  



### Download R language
The [R project main page](https://www.r-project.org/) in the **Getting Started**
section has a link to available CRAN mirrors to download R from, which will be
either the **O-Cloud** option or my country of choice, **USA**. There are 11
different USA institution options, I picked the Iowa State University mirror, which directed me to three download R options, and I used **Download R for Windows**, since I have a Windows operating system. On the download page, I chose
**base** or **install R for the first time**, doesn't matter they both link to the same place. Finally I made it to the actual download link I want, listed at the top of the page as **Download R 3.4.3 for Windows**, which will start the installation wizard for setup. 

Technically it is possible to use just the R terminal to run commands, but the
Rstudio shell is much more powerful and user friendly. Be kind to yourself, enjoy the GUI interface. 

### Download Rstudio, an integrated development environment (IDE)
The [web address](https://posit.co/downloads/) used to be "Rstudio.com", but this now redirects to "posit.co", so don't get confused about the site name change, there is still a free option. Scrolling to the bottom of the page shows two download options with features listed **RStudio Desktop Open Source Edition (AGPL v3)** or **RStudio Desktop Pro Posit Licensing Agreement**, there is no reason
to pay for the pro version unless working for a company, in which case they should be paying for access. The next page shows options for different operating
systems, I chose the download for **Windows 10/11 RSTUDIO-2022.12.0-353.EXE**.
Once again, open the file after downloaded to start the installation wizard. 



